### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by case-eee** [drod1000/lobbify#31]
1. I wonder if we can create a method to help you with this gsub rather than putting it directly in the controller action? Also - what happens if a user enters it in downcased in the url? will it still work?

```ruby
  def show
    @name = params[:name].gsub("_"," ")
    @politician = Politician.find_by(name: @name)
  end
```

2. `carts#index` is really really long. can we maybe create a PORO for this?

3. can we use a path helper here rather than hardcoding?
```ruby
        <td><%= link_to "Remove", "/carts/#{content.first.id}", method: :delete, class: "btn btn-danger btn-sm" %></td>
```

4. tests are looking good 👍 

5. if we did create a PORO for number 2 above, we wouldn't need to call `@contents.first` on every line in the `cart#index` view 👍 

overall looking good @njgheorghita @Laszlo-JFLMTCO @Dpalazzari @drod1000

**Comment by Laszlo-JFLMTCO** [comment]
@njgheorghita @Dpalazzari @drod1000 I opened up `firstfive-refactor` refactor branch, that covers everything except item 3 from Casey's feedback. Based on recent analysis, I fear we might have to rewrite our cart related routes. I will work with Casey and Sal tomorrow to see if we can fix it with the current route definitions.
